plugin: amazon.aws.aws_ec2
regions:
  - eu-west-1
filters:
  tag:Name: Terraform-ASG-Instance
  "instance-state-name": "running"
keyed_groups:
  - key: tags.Name
    prefix: tag
compose:
  ansible_host: public_ip_address
  ansible_user: "'ubuntu'"
  ansible_ssh_private_key_file: "'../../aws/my-key-pair.pem'"