- name: Download CloudWatch Agent
  get_url:
    url: "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
    dest: "/tmp/amazon-cloudwatch-agent.deb"
    mode: '0644'
- name: Install CloudWatch Agent
  apt:
    deb: "/tmp/amazon-cloudwatch-agent.deb"
- name: Start CloudWatch Agent
  systemd:
    name: amazon-cloudwatch-agent
    state: started
    enabled: yes
